---
language: python
python:
  - "3.6"
install:
  - pip install s3cmd
jobs:
  include:
    - stage: deploy-test
      script: make deploy-test
    - stage: test-test
      script: make test-test
    - stage: deploy-prod
      script: make deploy-prod
      if: branch = master
    - stage: test-prod
      script: make test-prod
      if: branch = master
