account_id = "779f26d6062518fa03d78247becfd24c"
name = "ip"
type = "javascript"
workers_dev = true

[env.production]
route = "myhro.info/ip*"
workers_dev = false
zone_id = "dbe71f84a9e980bcfd36c2f2fda5e825"
