---
name: Deploy
on:
  - push
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Dependencies
        run: |
          npm ci
      - name: Deploy
        env:
          BRANCH: ${{ github.REF_NAME }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          make deploy
