---
name: Main
on:
  - push
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          npm ci
          pip install yamllint==1.26.*
      - name: Check
        run: |
          make check
          make lint
          make yamllint
