---
name: Main
on:
  - push
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          npm ci
          pip install yamllint==1.26.*
      - name: QA
        run: |
          make check
          make lint
          make tsc
          make yamllint
