name: Site
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install s3cmd
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          make deploy
  test:
    runs-on: ubuntu-18.04
    needs: deploy
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bats
      - name: Test
        run: |
          make test
  deploy-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install s3cmd
      - name: Deploy Production
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          make deploy-prod
  test-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: deploy-prod
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bats
      - name: Test Production
        run: |
          make test-prod
