name: Workers
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          cd workers/
          make -C heroku/ deps
          make -C heroku/ deploy
          make -C ip/ deps
          make -C ip/ deploy
          make -C malvados/ deps
          make -C malvados/ deploy
          make -C myhro-net/ deps
          make -C myhro-net/ deploy
  deploy-prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Deploy Production
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          cd workers/
          make -C heroku/ deps
          make -C heroku/ deploy-prod
          make -C ip/ deps
          make -C ip/ deploy-prod
          make -C malvados/ deps
          make -C malvados/ deploy-prod
          make -C myhro-net/ deps
          make -C myhro-net/ deploy-prod
